START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_schema = 'fitness' 
                   AND table_name = 'WorkoutSessions' 
                   AND column_name = 'ClientId') THEN
        ALTER TABLE fitness."WorkoutSessions" ADD "ClientId" integer;
    END IF;
END $$;


DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_schema = 'fitness' 
                   AND table_name = 'WorkoutSessions' 
                   AND column_name = 'TrainerId') THEN
        ALTER TABLE fitness."WorkoutSessions" ADD "TrainerId" integer;
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS fitness."WorkoutExercises" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "WorkoutSessionId" integer NOT NULL,
    "ExerciseId" integer NOT NULL,
    "Sets" integer NOT NULL DEFAULT 0,
    "Repetitions" integer NOT NULL DEFAULT 0,
    "Weight" numeric(5,2),
    CONSTRAINT "PK_WorkoutExercises" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WorkoutExercises_Exercises_ExerciseId" FOREIGN KEY ("ExerciseId") REFERENCES fitness."Exercises" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_WorkoutExercises_WorkoutSessions_WorkoutSessionId" FOREIGN KEY ("WorkoutSessionId") REFERENCES fitness."WorkoutSessions" ("Id") ON DELETE CASCADE
);


CREATE INDEX IF NOT EXISTS "IX_WorkoutSessions_ClientId" ON fitness."WorkoutSessions" ("ClientId");

CREATE INDEX IF NOT EXISTS "IX_WorkoutSessions_TrainerId" ON fitness."WorkoutSessions" ("TrainerId");

CREATE UNIQUE INDEX IF NOT EXISTS idx_workout_exercise_unique ON fitness."WorkoutExercises" ("WorkoutSessionId", "ExerciseId");

CREATE INDEX IF NOT EXISTS "IX_WorkoutExercises_ExerciseId" ON fitness."WorkoutExercises" ("ExerciseId");

-- Add foreign key constraints if they don't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints 
                   WHERE constraint_schema = 'fitness' 
                   AND constraint_name = 'FK_WorkoutSessions_Clients_ClientId') THEN
        ALTER TABLE fitness."WorkoutSessions" ADD CONSTRAINT "FK_WorkoutSessions_Clients_ClientId" 
            FOREIGN KEY ("ClientId") REFERENCES fitness."Clients" ("Id") ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints 
                   WHERE constraint_schema = 'fitness' 
                   AND constraint_name = 'FK_WorkoutSessions_Trainers_TrainerId') THEN
        ALTER TABLE fitness."WorkoutSessions" ADD CONSTRAINT "FK_WorkoutSessions_Trainers_TrainerId" 
            FOREIGN KEY ("TrainerId") REFERENCES fitness."Trainers" ("Id") ON DELETE SET NULL;
    END IF;
END $$;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260131125414_AddRelationships', '8.0.10');

COMMIT;

